# Generated by Django 5.0.1 on 2024-01-07 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_category_parent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.category",
            ),
        ),
    ]
