# Generated by Django 5.0.1 on 2024-01-07 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_category_parent_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="parent_id",
            new_name="parent",
        ),
    ]
