# Generated by Django 5.0.1 on 2024-01-12 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_product_discount_price_alter_product_vendor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
    ]
