# Generated by Django 5.0.1 on 2024-01-12 03:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_alter_category_options_vendor_joined_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("slug", "name", "category", "vendor")},
        ),
    ]
