# Generated by Django 5.0.1 on 2024-01-12 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_alter_product_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="inventory.vendor",
            ),
        ),
    ]
