# Generated by Django 5.0.1 on 2024-01-12 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_remove_order_customer_remove_orderitem_order_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="vendor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_vendor",
                to="inventory.vendor",
            ),
            preserve_default=False,
        ),
    ]
